### ISSUE TITLE
Tag a release 

### ISSUE THREAD

**Issue by saschagrunert** [seccomp/containers-golang#14]
I think we could tag a new release after all these changes, WDYT? This would ultimately unblock https://github.com/cri-o/cri-o/pull/2523 to me.

**Comment by vrothberg** [comment]
Sounds good to me. But lets bump the `minor` version because of the new API.

**Comment by rhatdan** [comment]
:+1:

**Comment by saschagrunert** [comment]
Should I do it? I guess I have the power now... :)

**Comment by rhatdan** [comment]
Go for it.

**Comment by saschagrunert** [comment]
Closed with v0.3.0
