### ISSUE TITLE
Error adding seccomp rule for syscall socket: requested action matches default action of filter

### ISSUE THREAD

**Issue by saschagrunert** [seccomp/containers-golang#28]
Hey,

I'm not sure if we introduced a regression in https://github.com/seccomp/containers-golang/commit/f318ea962a1228ea9f6a2825b0051b2144699a16. I was working on updating the golang dependencies in https://github.com/cri-o/cri-o/pull/3927 and noticed the following error on running the integration tests:

```
time="2020-07-06T15:05:20+02:00" level=fatal msg="Creating container failed: rpc error: code = Unknown desc = container create failed: time=\"2020-07-06T15:05:20+02:00\" level=error msg=\"container_linux.go:349: starting container process caused \\\"error adding seccomp rule for syscall socket: requested action matches default action of filter\\\"\"\ncontainer_linux.go:349: starting container process caused \"error adding seccomp rule for syscall socket: requested action matches default action of filter\"\n"
```

I see that libpod already uses v0.5.0, are there any other issues in relation to that already known?

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by pcmoore** [comment]
Considering that this repo has migrated away, I'm going to close this issue.  @saschagrunert if this is still a problem I think you know what to do :)
