### ISSUE TITLE
New API for validating seccomp profiles

### ISSUE THREAD

**Issue by saschagrunert** [seccomp/containers-golang#34]
Hey, it would be nice to have an API to validate a seccomp profile from a given JSON string. WDYT?

I guess we have to verify, that the profile:

- can be unmarshalled
- contains a default action and at least one syscall
- contains either an architecture or an archmap but not both together
- the syscalls are available on the system (?)
- …

Do you see an easier way to validate a profile, maybe directly with libseccomp?

**Comment by vrothberg** [comment]
I think we have to accept anything that runc and crun accept (or generally speaking what the runtime spec [defines](https://github.com/opencontainers/runtime-spec/blob/278a7d747c17521625b723ac1361d006ba4a3bb4/config-linux.md#seccomp)) to prevent regressions. Doesn't runc or the runtime-tools provide an API to compile/validate a profile?  

> contains a default action and at least one syscall

... and ...

> the syscalls are available on the system (?)

seem like potential regressions since runc and crun would accept such profiles (I didn't check).

**Comment by saschagrunert** [comment]
> I think we have to accept anything that runc and crun accept (or generally speaking what the runtime spec [defines](https://github.com/opencontainers/runtime-spec/blob/278a7d747c17521625b723ac1361d006ba4a3bb4/config-linux.md#seccomp)) to prevent regressions. Doesn't runc or the runtime-tools provide an API to compile/validate a profile?

I don't wanna rely on libcontainer as library to be honest. And I think the runtime spec mostly relies on the JSON unmarshalling. Technically runc would allow to load a profile which does not contain any architecture :shrug: 

I agree that adding additional checks in this library may cause regressions, on the other hand I saw this:
https://github.com/seccomp/containers-golang/blob/b08e0ab374fb901c2708044eeed91bafaef37f48/seccomp_linux.go#L75-L78

We _assume_ that seccomp is disabled, but if that's not the case then the profile might be clearly wrong, right? Don't we wanna error in such a case? :thinking:

**Comment by vrothberg** [comment]
> We assume that seccomp is disabled, but if that's not the case then the profile might be clearly wrong, right?

The spec lists the default action to be required while syscalls are optional.

> Don't we wanna error in such a case?

I don't feel strongly about it. In the end it depends where we want to position this library. I think that any stricter checks should be done by the runtimes.

@giuseppe what do you think?

**Comment by saschagrunert** [comment]
I was working on migrating parts from libcontainer into this library (or containers/common if we migrate):
https://github.com/seccomp/containers-golang/compare/master...openSUSE:validate

I could refactor the code to be fully testable, whereas we could re-use the code in runc and in the seccomp-operator. WDYT? I would ask the runc maintainers if they're fine with the idea, too.

**Comment by saschagrunert** [comment]
Implementing the feature in containers/common.
