### ISSUE TITLE
seccomp.json is invalid with runc

### ISSUE THREAD

**Issue by baude** [seccomp/containers-golang#40]
The current seccomp,json fails to work with podman and runc.  this has broken our upstream CI testing.   can someone with stronger seccomp understanding please fix this and cut a new version?

**Comment by rhatdan** [comment]
There are new features going into this library, could there be something that is breaking older runc in the seccomp.json file.

I opened a PR to get fixes we have in fedora back into the upstream.

**Comment by mheon** [comment]
The problem: there is a conditional syscall for Socket with a default action that is the same as that of the filter. `crun` is of the opinion that this is fine and adds the rule. `runc` disagrees and blows up.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
the issue with older runc is that it doesn't know about "errnoRet" that was recently added to the OCI specs.  The last release of runc supports it.

For older runc versions we need to use an older seccomp.json configuration

**Comment by rhatdan** [comment]
We had better make sure the version of runc gets updated on RHEL8.3 then.  @jnovy FYI
