### ISSUE TITLE
Consider migrating this repository into github.com/containers/common

### ISSUE THREAD

**Issue by saschagrunert** [seccomp/containers-golang#41]
The library `containers/common` already contains the bits for AppArmor and Capabilities so I think it would be a good idea to migrate this library into it as well. A benefit would be to unify the CI and reduce the amount of vendored dependencies from conumsers like CRI-O.

Referencing discussion in https://github.com/containers/common/issues/270.

**Comment by vrothberg** [comment]
SGTM :+1:

**Comment by rhatdan** [comment]
We are going to migrate this REPO to containers/common in one week.  Speak now or forever hold your peace.

**Comment by saschagrunert** [comment]
https://github.com/containers/common/pull/276 is merged, to we wanna make this repository read-only?
