### ISSUE TITLE
add CI

### ISSUE THREAD

**Issue by vrothberg** [seccomp/containers-golang#5]
The projects needs some CI :)

**Comment by rhatdan** [comment]
I guess so.

**Comment by saschagrunert** [comment]
I guess the only thing go be done is to press the "Start Building" button here:
https://circleci.com/setup-project/gh/seccomp/containers-golang

And then enable “Build forked Pull requests” here: https://circleci.com/gh/seccomp/containers-golang/edit#advanced-settings

**Comment by rhatdan** [comment]
```
I guess the only thing go be done is to press the "Start Building" button here:
https://circleci.com/setup-project/gh/seccomp/containers-golang
```
I don't see any projects here

I have enabled the "Build forked Pull reguests"

**Comment by rhatdan** [comment]
```
CircleCI helps you ship better code, faster. To kick things off, you'll need to add a config.yml file to your project, and start building. After that, we'll start a new build for you each time someone pushes a new commit.

Select from the following options to generate a sample .yml for your project.
Project not found.
```

**Comment by saschagrunert** [comment]
The problem might be that the app is not installed in the `seccomp` organization, let's see If I can trigger that somehow.

**Comment by saschagrunert** [comment]
No, I cannot see the organization because I'm not part of it. :(

**Comment by rhatdan** [comment]
Yes I went looking for settings to add you to seccomp/containers-golang, but I don't have the power.  I guess I have to be an administrator of github.com/seccomp to add people.  I will ask @pcmoore to give me the power.

**Comment by saschagrunert** [comment]
Sounds good, thank you :pray:

**Comment by saschagrunert** [comment]
I requested access for the repo and CircleCi, the owner of the organization should have received a mail about this.

**Comment by rhatdan** [comment]
I added you and @vrothberg as Admins of this repo.

**Comment by vrothberg** [comment]
Thanks, Dan :man_dancing:

**Comment by saschagrunert** [comment]
Thanks, but I guess the mail about the request goes to the organization owner, @pcmoore? :)

**Comment by pcmoore** [comment]
Yep, it looks like I got the email and I have no idea how to delegate that to you guys for this repo, sorry.

Anyway, I just approved the CircleCI request, if you need anything like that in the future you know where to find me.

**Comment by saschagrunert** [comment]
It's running: https://circleci.com/gh/seccomp/workflows/containers-golang :tada: Thanks :pray:
